//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Handles ChartOfAccountCreatedEvent: triggered when a new chart of account is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.ChartOfAccounts.EventHandlers;

public class ChartOfAccountCreatedEventHandler : INotificationHandler<ChartOfAccountCreatedEvent>
{
    private readonly ILogger<ChartOfAccountCreatedEventHandler> _logger;

    public ChartOfAccountCreatedEventHandler(
        ILogger<ChartOfAccountCreatedEventHandler> logger
        )
    {
        _logger = logger;
    }
    
    public Task Handle(ChartOfAccountCreatedEvent notification, CancellationToken cancellationToken)
    {
        _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
        return Task.CompletedTask;
    }
}
