//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for deleting InvoiceItem(s).
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.InvoiceItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.InvoiceItems.Commands.Delete;

public class DeleteInvoiceItemCommand : ICacheInvalidatorRequest<Result<string>>
{
    public string[] Ids { get; set; } = Array.Empty<string>();
    public string CacheKey => InvoiceItemCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => InvoiceItemCacheKey.Tags;
}

public class DeleteInvoiceItemCommandHandler : IRequestHandler<DeleteInvoiceItemCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public DeleteInvoiceItemCommandHandler(IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<string>> Handle(DeleteInvoiceItemCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.InvoiceItems.Where(x => request.Ids.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
            item.AddDomainEvent(new InvoiceItemDeletedEvent(item));
            db.InvoiceItems.Remove(item);
        }
        var result = await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync($"Deleted {result} invoice items.");
    }
}
