//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for creating a new BillItem.
// Uses caching invalidation and domain events for data consistency.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.BillItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.BillItems.Commands.Create;

public class CreateBillItemCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Bill ID")]
    public string? BillID { get; set; }
    
    [Description("Item Name")]
    public string? ItemName { get; set; }
    
    [Description("Quantity")]
    public int Quantity { get; set; }
    
    [Description("Unit Price")]
    public decimal UnitPrice { get; set; }
    
    [Description("Line Total")]
    public decimal LineTotal { get; set; }

    public string CacheKey => BillItemCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => BillItemCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateBillItemCommand, BillItem>(MemberList.None);
        }
    }
}

public class CreateBillItemCommandHandler : IRequestHandler<CreateBillItemCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public CreateBillItemCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(CreateBillItemCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = _mapper.Map<BillItem>(request);
        item.AddDomainEvent(new BillItemCreatedEvent(item));
        db.BillItems.Add(item);
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
