//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Validator for CreateChartOfAccountCommand.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.ChartOfAccounts.Commands.Create;

public class CreateChartOfAccountCommandValidator : AbstractValidator<CreateChartOfAccountCommand>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public CreateChartOfAccountCommandValidator(IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
        
        RuleFor(v => v.Name)
            .MaximumLength(256)
            .NotEmpty();
            
        RuleFor(v => v.AccountType)
            .IsInEnum();
            
        RuleFor(v => v.Description)
            .MaximumLength(500);
    }
}
