//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for creating a new ChartOfAccount.
// Uses caching invalidation and domain events for data consistency.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.ChartOfAccounts.Caching;

namespace CleanArchitecture.Blazor.Application.Features.ChartOfAccounts.Commands.Create;

public class CreateChartOfAccountCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Account Name")]
    public string Name { get; set; } = string.Empty;
    
    [Description("Account Type")]
    public AccountType AccountType { get; set; }
    
    [Description("Sub Account Of")]
    public string? SubAccountOf { get; set; }
    
    [Description("Description")]
    public string? Description { get; set; }
    
    [Description("Is Active")]
    public bool IsActive { get; set; } = true;

    public string CacheKey => ChartOfAccountCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => ChartOfAccountCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateChartOfAccountCommand, ChartOfAccount>(MemberList.None)
                .ForMember(dest => dest.AccountName, opt => opt.MapFrom(src => src.Name));
        }
    }
}

public class CreateChartOfAccountCommandHandler : IRequestHandler<CreateChartOfAccountCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public CreateChartOfAccountCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(CreateChartOfAccountCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = _mapper.Map<ChartOfAccount>(request);
        item.AddDomainEvent(new ChartOfAccountCreatedEvent(item));
        db.ChartOfAccounts.Add(item);
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
