//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Validator for ImportBillsCommand: enforces file requirements for Bill imports.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Bills.Commands.Import;

public class ImportBillsCommandValidator : AbstractValidator<ImportBillsCommand>
{
    public ImportBillsCommandValidator()
    {
        RuleFor(v => v.Data).NotNull().NotEmpty();
        RuleFor(v => v.FileName).NotEmpty().MaximumLength(255);
    }
}
