//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Import command & template for bills.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Bills.DTOs;
using CleanArchitecture.Blazor.Application.Features.Bills.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Bills.Commands.Import;

public class ImportBillsCommand : ICacheInvalidatorRequest<Result<int>>
{
    public string FileName { get; set; }
    public byte[] Data { get; set; }
    public string CacheKey => BillCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => BillCacheKey.Tags;
    
    public ImportBillsCommand(string fileName, byte[] data)
    {
        FileName = fileName;
        Data = data;
    }
}

public record class CreateBillsTemplateCommand : IRequest<Result<byte[]>>
{
}

public class ImportBillsCommandHandler :
    IRequestHandler<CreateBillsTemplateCommand, Result<byte[]>>,
    IRequestHandler<ImportBillsCommand, Result<int>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IStringLocalizer<ImportBillsCommandHandler> _localizer;
    private readonly IExcelService _excelService;
    private readonly BillDto _dto = new();
    private readonly IMapper _mapper;

    public ImportBillsCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper,
        IExcelService excelService,
        IStringLocalizer<ImportBillsCommandHandler> localizer)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
        _excelService = excelService;
        _localizer = localizer;
    }

    #nullable disable warnings
    public async Task<Result<int>> Handle(ImportBillsCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);

        var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, BillDto, object?>>
        {
            { _localizer[_dto.GetMemberDescription(x => x.VendorId)], (row, item) => item.VendorId = row[_localizer[_dto.GetMemberDescription(x => x.VendorId)]].ToString() },
            { _localizer[_dto.GetMemberDescription(x => x.BillDate)], (row, item) => item.BillDate = Convert.ToDateTime(row[_localizer[_dto.GetMemberDescription(x => x.BillDate)]]) },
            { _localizer[_dto.GetMemberDescription(x => x.DueDate)], (row, item) => item.DueDate = Convert.ToDateTime(row[_localizer[_dto.GetMemberDescription(x => x.DueDate)]]) },
            { _localizer[_dto.GetMemberDescription(x => x.TotalAmount)], (row, item) => item.TotalAmount = Convert.ToDecimal(row[_localizer[_dto.GetMemberDescription(x => x.TotalAmount)]]) },
            { _localizer[_dto.GetMemberDescription(x => x.Status)], (row, item) => item.Status = Enum.Parse<BillStatus>(row[_localizer[_dto.GetMemberDescription(x => x.Status)]].ToString()) }
        }, _localizer[_dto.GetClassDescription()]);

        if (result.Succeeded && result.Data is not null)
        {
            foreach (var dto in result.Data)
            {
                var exists = await db.Bills.AnyAsync(x => x.VendorId == dto.VendorId && x.BillDate == dto.BillDate && x.TotalAmount == dto.TotalAmount, cancellationToken);
                if (!exists)
                {
                    var item = _mapper.Map<Bill>(dto);
                    // add create domain events if this entity implement the IHasDomainEvent interface
                    // item.AddDomainEvent(new BillCreatedEvent(item));
                    await db.Bills.AddAsync(item, cancellationToken);
                }
            }
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(result.Data.Count());
        }
        else
        {
            return await Result<int>.FailureAsync(result.Errors);
        }
    }

    public async Task<Result<byte[]>> Handle(CreateBillsTemplateCommand request, CancellationToken cancellationToken)
    {
        var fields = new string[]
        {
            _localizer[_dto.GetMemberDescription(x => x.VendorId)],
            _localizer[_dto.GetMemberDescription(x => x.BillDate)],
            _localizer[_dto.GetMemberDescription(x => x.DueDate)],
            _localizer[_dto.GetMemberDescription(x => x.TotalAmount)],
            _localizer[_dto.GetMemberDescription(x => x.Status)]
        };
        var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
        return await Result<byte[]>.SuccessAsync(result);
    }
}
