//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Defines permission constants for chart of account operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Chart Of Account Permissions")]
    [Description("Set permissions for chart of account operations.")]
    public static class ChartOfAccounts
    {
        [Description("Allows viewing chart of account details.")]
        public const string View = "Permissions.ChartOfAccounts.View";
        [Description("Allows creating chart of account records.")]
        public const string Create = "Permissions.ChartOfAccounts.Create";
        [Description("Allows modifying existing chart of account details.")]
        public const string Edit = "Permissions.ChartOfAccounts.Edit";
        [Description("Allows deleting chart of account records.")]
        public const string Delete = "Permissions.ChartOfAccounts.Delete";
        [Description("Allows printing chart of account details.")]
        public const string Print = "Permissions.ChartOfAccounts.Print";
        [Description("Allows searching chart of account records.")]
        public const string Search = "Permissions.ChartOfAccounts.Search";
        [Description("Allows exporting chart of account records.")]
        public const string Export = "Permissions.ChartOfAccounts.Export";
        [Description("Allows importing chart of account records.")]
        public const string Import = "Permissions.ChartOfAccounts.Import";
    }
}

public class ChartOfAccountsAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}

