//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// GeneralLedgerDto: transfers general ledger data between layers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.GeneralLedgers.DTOs;

[Description("General Ledger")]
public class GeneralLedgerDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Entry ID")]
    public string? EntryID { get; set; }
    
    [Description("Account ID")]
    public string? AccountID { get; set; }
    
    [Description("Debit")]
    public decimal Debit { get; set; }
    
    [Description("Credit")]
    public decimal Credit { get; set; }
    
    [Description("Memo")]
    public string? Memo { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<GeneralLedger, GeneralLedgerDto>(MemberList.None);
            CreateMap<GeneralLedgerDto, GeneralLedger>(MemberList.None);
        }
    }
}
