//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Defines static methods and properties for managing cache keys and expiration 
//       settings for BillItem-related data.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.BillItems.Caching;

public static class BillItemCacheKey
{
    public const string GetAllCacheKey = "all-BillItems";
    public static string GetPaginationCacheKey(string parameters) {
        return $"BillItemCacheKey:BillItemsWithPaginationQuery,{parameters}";
    }
    public static string GetByBillIdCacheKey(string billId) {
        return $"BillItemCacheKey:GetByBillIdCacheKey,{billId}";
    }
    public static IEnumerable<string>? Tags => new string[] { "billitem" };

    private static readonly object _tokenLock = new object();
    private static CancellationTokenSource _tokenSource = new CancellationTokenSource();

    public static CancellationToken GetOrCreateToken()
    {
        lock (_tokenLock)
        {
            if (_tokenSource.Token.IsCancellationRequested)
            {
                _tokenSource = new CancellationTokenSource();
            }
            return _tokenSource.Token;
        }
    }

    public static void Refresh()
    {
        lock (_tokenLock)
        {
            if (!_tokenSource.Token.IsCancellationRequested)
            {
                _tokenSource.Cancel();
            }
        }
    }
}
