//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Query for retrieving a single vendor by its unique identifier.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vendors.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Queries.GetById;

public class GetVendorByIdQuery : ICacheableRequest<Result<VendorDto>>
{
    public required string Id { get; set; }
    public string CacheKey => VendorCacheKey.GetByIdCacheKey($"{Id}");
    public IEnumerable<string>? Tags => VendorCacheKey.Tags;
}

public class GetVendorByIdQueryHandler : IRequestHandler<GetVendorByIdQuery, Result<VendorDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public GetVendorByIdQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<VendorDto>> Handle(GetVendorByIdQuery request, CancellationToken cancellationToken)
    {
        await using var context = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await context.Vendors
            .Where(x => x.Id == request.Id)
            .ProjectTo<VendorDto>(_mapper.ConfigurationProvider)
            .FirstOrDefaultAsync(cancellationToken);

        if (item == null)
        {
            return await Result<VendorDto>.FailureAsync($"Vendor with id: [{request.Id}] not found.");
        }

        return await Result<VendorDto>.SuccessAsync(item);
    }
}
