//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for updating a BillItem.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.BillItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.BillItems.Commands.Update;

public class UpdateBillItemCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Bill Id")]
    public string? BillID { get; set; }
    
    [Description("Item Name")]
    public string? ItemName { get; set; }
    
    [Description("Quantity")]
    public int Quantity { get; set; }
    
    [Description("Unit Price")]
    public decimal UnitPrice { get; set; }
    
    [Description("Line Total")]
    public decimal LineTotal { get; set; }

    public string CacheKey => BillItemCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => BillItemCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateBillItemCommand, BillItem>(MemberList.None);
        }
    }
}

public class UpdateBillItemCommandHandler : IRequestHandler<UpdateBillItemCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public UpdateBillItemCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(UpdateBillItemCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.BillItems.FindAsync(new object[] { request.Id }, cancellationToken);
        if (item == null)
        {
            return await Result<string>.FailureAsync($"Bill Item with id: {request.Id} not found.");
        }
        item = _mapper.Map(request, item);
        item.AddDomainEvent(new BillItemUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
