//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Query for getting all InvoiceItems.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.InvoiceItems.DTOs;
using CleanArchitecture.Blazor.Application.Features.InvoiceItems.Caching;
using Microsoft.Extensions.Caching.Memory;

namespace CleanArchitecture.Blazor.Application.Features.InvoiceItems.Queries.GetAll;

public class GetAllInvoiceItemsQuery : ICacheableRequest<IEnumerable<InvoiceItemDto>>
{
    public string CacheKey => InvoiceItemCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags { get; }

    public MemoryCacheEntryOptions? Options => new MemoryCacheEntryOptions
    {
        AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(30)
    };
}

public class GetAllInvoiceItemsQueryHandler : IRequestHandler<GetAllInvoiceItemsQuery, IEnumerable<InvoiceItemDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public GetAllInvoiceItemsQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<IEnumerable<InvoiceItemDto>> Handle(GetAllInvoiceItemsQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.InvoiceItems
            .OrderBy(x => x.Name)
            .ToListAsync(cancellationToken);
        return _mapper.Map<List<InvoiceItemDto>>(data);
    }
}
