//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Validator for ImportInvoicesCommand: enforces file requirements for Invoice imports.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Invoices.Commands.Import;

public class ImportInvoicesCommandValidator : AbstractValidator<ImportInvoicesCommand>
{
    public ImportInvoicesCommandValidator()
    {
        RuleFor(v => v.Data).NotNull().NotEmpty();
        RuleFor(v => v.FileName).NotEmpty().MaximumLength(255);
    }
}
