//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Defines permission constants for invoice operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Invoice Permissions")]
    [Description("Set permissions for invoice operations.")]
    public static class Invoices
    {
        [Description("Allows viewing invoice details.")]
        public const string View = "Permissions.Invoices.View";
        [Description("Allows creating invoice records.")]
        public const string Create = "Permissions.Invoices.Create";
        [Description("Allows modifying existing invoice details.")]
        public const string Edit = "Permissions.Invoices.Edit";
        [Description("Allows deleting invoice records.")]
        public const string Delete = "Permissions.Invoices.Delete";
        [Description("Allows printing invoice details.")]
        public const string Print = "Permissions.Invoices.Print";
        [Description("Allows searching invoice records.")]
        public const string Search = "Permissions.Invoices.Search";
        [Description("Allows exporting invoice records.")]
        public const string Export = "Permissions.Invoices.Export";
        [Description("Allows importing invoice records.")]
        public const string Import = "Permissions.Invoices.Import";
    }
}

public class InvoicesAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
