//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for deleting Bill(s).
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Bills.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Bills.Commands.Delete;

public class DeleteBillCommand : ICacheInvalidatorRequest<Result<string>>
{
    public string[] Ids { get; set; } = Array.Empty<string>();
    public string CacheKey => BillCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => BillCacheKey.Tags;
}

public class DeleteBillCommandHandler : IRequestHandler<DeleteBillCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public DeleteBillCommandHandler(IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<string>> Handle(DeleteBillCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Bills.Where(x => request.Ids.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
            item.AddDomainEvent(new BillDeletedEvent(item));
            db.Bills.Remove(item);
        }
        var result = await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync($"Deleted {result} bills.");
    }
}
