//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Advanced filter and specification for Invoice queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Invoices.Specifications;

public enum InvoiceListView
{
    [Description("All")]
    All,
    [Description("Open")]
    Open,
    [Description("Paid")]
    Paid,
    [Description("Overdue")]
    Overdue
}

public class InvoiceAdvancedFilter : PaginationFilter
{
    public InvoiceListView ListView { get; set; } = InvoiceListView.All;
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }
    public string? CustomerID { get; set; }
    public InvoiceStatus? Status { get; set; }
    public decimal? MinAmount { get; set; }
    public decimal? MaxAmount { get; set; }
}

public class InvoiceAdvancedSpecification : Specification<Invoice>
{
    public InvoiceAdvancedSpecification(InvoiceAdvancedFilter filter)
    {
        Query.Where(q => q.CustomerID != null)
             .Where(filter.Keyword, !string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.CustomerID == filter.CustomerID, !string.IsNullOrEmpty(filter.CustomerID))
             .Where(q => q.Status == filter.Status, filter.Status.HasValue)
             .Where(q => q.InvoiceDate >= filter.StartDate, filter.StartDate.HasValue)
             .Where(q => q.InvoiceDate <= filter.EndDate, filter.EndDate.HasValue)
             .Where(q => q.TotalAmount >= filter.MinAmount, filter.MinAmount.HasValue)
             .Where(q => q.TotalAmount <= filter.MaxAmount, filter.MaxAmount.HasValue);

        switch (filter.ListView)
        {
            case InvoiceListView.All:
                break;
            case InvoiceListView.Open:
                Query.Where(q => q.Status == InvoiceStatus.Open);
                break;
            case InvoiceListView.Paid:
                Query.Where(q => q.Status == InvoiceStatus.Paid);
                break;
            case InvoiceListView.Overdue:
                Query.Where(q => q.Status == InvoiceStatus.Overdue);
                break;
        }
    }
}
