//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for updating a GeneralLedger.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.GeneralLedgers.Caching;

namespace CleanArchitecture.Blazor.Application.Features.GeneralLedgers.Commands.Update;

public class UpdateGeneralLedgerCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Entry ID")]
    public string? EntryID { get; set; }
    
    [Description("Account ID")]
    public string? AccountID { get; set; }
    
    [Description("Debit")]
    public decimal Debit { get; set; }
    
    [Description("Credit")]
    public decimal Credit { get; set; }
    
    [Description("Memo")]
    public string? Memo { get; set; }

    public string CacheKey => GeneralLedgerCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => GeneralLedgerCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateGeneralLedgerCommand, GeneralLedger>(MemberList.None);
        }
    }
}

public class UpdateGeneralLedgerCommandHandler : IRequestHandler<UpdateGeneralLedgerCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public UpdateGeneralLedgerCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(UpdateGeneralLedgerCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.GeneralLedgers.FindAsync(new object[] { request.Id }, cancellationToken);
        if (item == null)
        {
            return await Result<string>.FailureAsync($"General Ledger with id: {request.Id} not found.");
        }
        item = _mapper.Map(request, item);
        item.AddDomainEvent(new GeneralLedgerUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
