//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for deleting JournalEntry(s).
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.JournalEntries.Caching;

namespace CleanArchitecture.Blazor.Application.Features.JournalEntries.Commands.Delete;

public class DeleteJournalEntryCommand : ICacheInvalidatorRequest<Result<string>>
{
    public string[] Ids { get; set; } = Array.Empty<string>();
    public string CacheKey => JournalEntryCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => JournalEntryCacheKey.Tags;
}

public class DeleteJournalEntryCommandHandler : IRequestHandler<DeleteJournalEntryCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public DeleteJournalEntryCommandHandler(IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<string>> Handle(DeleteJournalEntryCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.JournalEntries.Where(x => request.Ids.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
            item.AddDomainEvent(new JournalEntryDeletedEvent(item));
            db.JournalEntries.Remove(item);
        }
        var result = await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync($"Deleted {result} journal entries.");
    }
}
