//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for updating a Vendor.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Commands.Update;

public class UpdateVendorCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Vendor Name")]
    public string Name { get; set; } = string.Empty;
    
    [Description("Billing Address")]
    public string? BillingAddress { get; set; }
    
    [Description("Contact Person")]
    public string? ContactPerson { get; set; }
    
    [Description("Email")]
    public string? Email { get; set; }
    
    [Description("Terms")]
    public string? Terms { get; set; }

    public string CacheKey => VendorCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => VendorCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateVendorCommand, Vendor>(MemberList.None)
                .ForMember(dest => dest.VendorName, opt => opt.MapFrom(src => src.Name));
        }
    }
}

public class UpdateVendorCommandHandler : IRequestHandler<UpdateVendorCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public UpdateVendorCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(UpdateVendorCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.Vendors.FindAsync(new object[] { request.Id }, cancellationToken);
        if (item == null)
        {
            return await Result<string>.FailureAsync($"Vendor with id: {request.Id} not found.");
        }
        item = _mapper.Map(request, item);
        item.AddDomainEvent(new VendorUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
