//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Query for retrieving a single invoice by its unique identifier.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Invoices.DTOs;
using CleanArchitecture.Blazor.Application.Features.Invoices.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Invoices.Queries.GetById;

public class GetInvoiceByIdQuery : ICacheableRequest<Result<InvoiceDto>>
{
    public required string Id { get; set; }
    public string CacheKey => InvoiceCacheKey.GetByIdCacheKey($"{Id}");
    public IEnumerable<string>? Tags => InvoiceCacheKey.Tags;
}

public class GetInvoiceByIdQueryHandler : IRequestHandler<GetInvoiceByIdQuery, Result<InvoiceDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public GetInvoiceByIdQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<InvoiceDto>> Handle(GetInvoiceByIdQuery request, CancellationToken cancellationToken)
    {
        await using var context = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await context.Invoices
            .Where(x => x.Id == request.Id)
            .ProjectTo<InvoiceDto>(_mapper.ConfigurationProvider)
            .FirstOrDefaultAsync(cancellationToken);

        if (item == null)
        {
            return await Result<InvoiceDto>.FailureAsync($"Invoice with id: [{request.Id}] not found.");
        }

        return await Result<InvoiceDto>.SuccessAsync(item);
    }
}
