//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Query for getting all GeneralLedgers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.GeneralLedgers.DTOs;
using CleanArchitecture.Blazor.Application.Features.GeneralLedgers.Caching;
using Microsoft.Extensions.Caching.Memory;

namespace CleanArchitecture.Blazor.Application.Features.GeneralLedgers.Queries.GetAll;

public class GetAllGeneralLedgersQuery : ICacheableRequest<IEnumerable<GeneralLedgerDto>>
{
    public string CacheKey => GeneralLedgerCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags { get; }

    public MemoryCacheEntryOptions? Options => new MemoryCacheEntryOptions
    {
        AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(30)
    };
}

public class GetAllGeneralLedgersQueryHandler : IRequestHandler<GetAllGeneralLedgersQuery, IEnumerable<GeneralLedgerDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public GetAllGeneralLedgersQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<IEnumerable<GeneralLedgerDto>> Handle(GetAllGeneralLedgersQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.GeneralLedgers
            .OrderBy(x => x.Created)
            .ToListAsync(cancellationToken);
        return _mapper.Map<List<GeneralLedgerDto>>(data);
    }
}
