//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Defines permission constants for bill operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Bill Permissions")]
    [Description("Set permissions for bill operations.")]
    public static class Bills
    {
        [Description("Allows viewing bill details.")]
        public const string View = "Permissions.Bills.View";
        [Description("Allows creating bill records.")]
        public const string Create = "Permissions.Bills.Create";
        [Description("Allows modifying existing bill details.")]
        public const string Edit = "Permissions.Bills.Edit";
        [Description("Allows deleting bill records.")]
        public const string Delete = "Permissions.Bills.Delete";
        [Description("Allows printing bill details.")]
        public const string Print = "Permissions.Bills.Print";
        [Description("Allows searching bill records.")]
        public const string Search = "Permissions.Bills.Search";
        [Description("Allows exporting bill records.")]
        public const string Export = "Permissions.Bills.Export";
        [Description("Allows importing bill records.")]
        public const string Import = "Permissions.Bills.Import";
    }
}

public class BillsAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
