//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// JournalEntryDto: transfers journal entry data between layers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.JournalEntries.DTOs;

[Description("Journal Entries")]
public class JournalEntryDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Date")]
    public DateTime Date { get; set; }
    
    [Description("Reference Number")]
    public string? ReferenceNumber { get; set; }
    
    [Description("Description")]
    public string? Description { get; set; }
    
    [Description("Source")]
    public string? Source { get; set; }
    
    [Description("Is Posted")]
    public bool IsPosted { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<JournalEntry, JournalEntryDto>(MemberList.None);
            CreateMap<JournalEntryDto, JournalEntry>(MemberList.None);
        }
    }
}
