//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for updating an Invoice.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Invoices.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Invoices.Commands.Update;

public class UpdateInvoiceCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Customer ID")]
    public string? CustomerID { get; set; }
    
    [Description("Invoice Date")]
    public DateTime InvoiceDate { get; set; }
    
    [Description("Due Date")]
    public DateTime DueDate { get; set; }
    
    [Description("Total Amount")]
    public decimal TotalAmount { get; set; }
    
    [Description("Status")]
    public InvoiceStatus Status { get; set; }

    public string CacheKey => InvoiceCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => InvoiceCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateInvoiceCommand, Invoice>(MemberList.None);
        }
    }
}

public class UpdateInvoiceCommandHandler : IRequestHandler<UpdateInvoiceCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public UpdateInvoiceCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(UpdateInvoiceCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.Invoices.FindAsync(new object[] { request.Id }, cancellationToken);
        if (item == null)
        {
            return await Result<string>.FailureAsync($"Invoice with id: {request.Id} not found.");
        }
        item = _mapper.Map(request, item);
        item.AddDomainEvent(new InvoiceUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
