//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for creating a new InvoiceItem.
// Uses caching invalidation and domain events for data consistency.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.InvoiceItems.Caching;

namespace CleanArchitecture.Blazor.Application.Features.InvoiceItems.Commands.Create;

public class CreateInvoiceItemCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Invoice Id")]
    public string? InvoiceID { get; set; }
    
    [Description("Item Name")]
    public string? ItemName { get; set; }
    
    [Description("Quantity")]
    public int Quantity { get; set; }
    
    [Description("Unit Price")]
    public decimal UnitPrice { get; set; }
    
    [Description("Line Total")]
    public decimal LineTotal { get; set; }

    public string CacheKey => InvoiceItemCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => InvoiceItemCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateInvoiceItemCommand, InvoiceItem>(MemberList.None);
        }
    }
}

public class CreateInvoiceItemCommandHandler : IRequestHandler<CreateInvoiceItemCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public CreateInvoiceItemCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(CreateInvoiceItemCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = _mapper.Map<InvoiceItem>(request);
        item.AddDomainEvent(new InvoiceItemCreatedEvent(item));
        db.InvoiceItems.Add(item);
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
