//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for deleting GeneralLedger(s).
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.GeneralLedgers.Caching;

namespace CleanArchitecture.Blazor.Application.Features.GeneralLedgers.Commands.Delete;

public class DeleteGeneralLedgerCommand : ICacheInvalidatorRequest<Result<string>>
{
    public string[] Ids { get; set; } = Array.Empty<string>();
    public string CacheKey => GeneralLedgerCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => GeneralLedgerCacheKey.Tags;
}

public class DeleteGeneralLedgerCommandHandler : IRequestHandler<DeleteGeneralLedgerCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public DeleteGeneralLedgerCommandHandler(IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<string>> Handle(DeleteGeneralLedgerCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.GeneralLedgers.Where(x => request.Ids.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
            item.AddDomainEvent(new GeneralLedgerDeletedEvent(item));
            db.GeneralLedgers.Remove(item);
        }
        var result = await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync($"Deleted {result} general ledger entries.");
    }
}
