//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command for adding/editing a bill entity with validation, mapping,
// domain events, and cache invalidation.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Bills.Caching;
using CleanArchitecture.Blazor.Application.Features.Bills.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Bills.Commands.AddEdit;

public class AddEditBillCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string? Id { get; set; }
    [Description("Vendor Id")]
    public string? VendorId { get; set; }
    [Description("Bill Date")]
    public DateTime BillDate { get; set; } = DateTime.Now;
    [Description("Due Date")]
    public DateTime DueDate { get; set; }
    [Description("Total Amount")]
    public decimal TotalAmount { get; set; }
    [Description("Status")]
    public BillStatus Status { get; set; } = BillStatus.Open;

    public string CacheKey => BillCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => BillCacheKey.Tags;

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<BillDto, AddEditBillCommand>(MemberList.None);
            CreateMap<AddEditBillCommand, Bill>(MemberList.None);
        }
    }
}

public class AddEditBillCommandHandler : IRequestHandler<AddEditBillCommand, Result<string>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public AddEditBillCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<string>> Handle(AddEditBillCommand request, CancellationToken cancellationToken)
    {
        await using var context = await _dbContextFactory.CreateAsync(cancellationToken);
        if (request.Id is not null)
        {
            var item = await context.Bills.FindAsync([request.Id], cancellationToken);
            if (item is null)
            {
                return await Result<string>.FailureAsync($"Bill with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
            await context.SaveChangesAsync(cancellationToken);
            return await Result<string>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Bill>(request);
            context.Bills.Add(item);
            await context.SaveChangesAsync(cancellationToken);
            return await Result<string>.SuccessAsync(item.Id);
        }
    }
}
