//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Validator for AddEditBillCommand: enforces field length and required property rules for Bill entities.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Bills.Commands.AddEdit;

public class AddEditBillCommandValidator : AbstractValidator<AddEditBillCommand>
{
    public AddEditBillCommandValidator()
    {
        RuleFor(v => v.VendorId).MaximumLength(100).NotEmpty();
        RuleFor(v => v.BillDate).NotEmpty();
        RuleFor(v => v.DueDate).NotEmpty().GreaterThanOrEqualTo(v => v.BillDate);
        RuleFor(v => v.TotalAmount).GreaterThan(0);
        RuleFor(v => v.Status).IsInEnum().NotNull();
    }
}
