﻿//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Handles BillCreatedEvent: triggered when a new bill is created.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Extensions.Logging;
using MediatR;
using CleanArchitecture.Blazor.Domain.Events;

namespace CleanArchitecture.Blazor.Application.Features.Bills.EventHandlers;

public class BillCreatedEventHandler(ILogger<BillCreatedEventHandler> logger) : INotificationHandler<BillCreatedEvent>
{
    public Task Handle(BillCreatedEvent notification, CancellationToken cancellationToken)
    {
        logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
        return Task.CompletedTask;
    }
}

