﻿//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Handles BillDeletedEvent: triggered when a bill is deleted.
// Extendable for additional actions (e.g., notifications, system updates).
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Extensions.Logging;
using MediatR;
using CleanArchitecture.Blazor.Domain.Events;

namespace CleanArchitecture.Blazor.Application.Features.Bills.EventHandlers;

public class BillDeletedEventHandler(ILogger<BillDeletedEventHandler> logger) : INotificationHandler<BillDeletedEvent>
{
    public Task Handle(BillDeletedEvent notification, CancellationToken cancellationToken)
    {
        logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
        return Task.CompletedTask;
    }
}

