//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Handles VendorCreatedEvent: triggered when a new vendor is created.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.Vendors.EventHandlers;

public class VendorCreatedEventHandler : INotificationHandler<VendorCreatedEvent>
{
    private readonly ILogger<VendorCreatedEventHandler> _logger;

    public VendorCreatedEventHandler(ILogger<VendorCreatedEventHandler> logger)
    {
        _logger = logger;
    }
    
    public Task Handle(VendorCreatedEvent notification, CancellationToken cancellationToken)
    {
        _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
        return Task.CompletedTask;
    }
}
