//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Handles VendorDeletedEvent: triggered when a vendor is deleted.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Features.Vendors.EventHandlers;

public class VendorDeletedEventHandler : INotificationHandler<VendorDeletedEvent>
{
    private readonly ILogger<VendorDeletedEventHandler> _logger;

    public VendorDeletedEventHandler(ILogger<VendorDeletedEventHandler> logger)
    {
        _logger = logger;
    }
    
    public Task Handle(VendorDeletedEvent notification, CancellationToken cancellationToken)
    {
        _logger.LogInformation("Handled domain event '{EventType}' with notification: {@Notification} ", notification.GetType().Name, notification);
        return Task.CompletedTask;
    }
}
