//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for deleting Vendor(s).
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Commands.Delete;

public class DeleteVendorCommand : ICacheInvalidatorRequest<Result<string>>
{
    public string[] Ids { get; set; } = Array.Empty<string>();
    public string CacheKey => VendorCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => VendorCacheKey.Tags;
}

public class DeleteVendorCommandHandler : IRequestHandler<DeleteVendorCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public DeleteVendorCommandHandler(IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<string>> Handle(DeleteVendorCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Vendors.Where(x => request.Ids.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
            item.AddDomainEvent(new VendorDeletedEvent(item));
            db.Vendors.Remove(item);
        }
        var result = await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync($"Deleted {result} vendors.");
    }
}
