//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for creating a new Customer.
// Uses caching invalidation and domain events for data consistency.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Customers.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Customers.Commands.Create;

public class CreateCustomerCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Customer Name")]
    public string Name { get; set; } = string.Empty;
    
    [Description("Billing Address")]
    public string? BillingAddress { get; set; }
    
    [Description("Contact Person")]
    public string? ContactPerson { get; set; }
    
    [Description("Email")]
    public string? Email { get; set; }
    
    [Description("Terms")]
    public string? Terms { get; set; }

    public string CacheKey => CustomerCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => CustomerCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreateCustomerCommand, Customer>(MemberList.None)
                .ForMember(dest => dest.CustomerName, opt => opt.MapFrom(src => src.Name));
        }
    }
}

public class CreateCustomerCommandHandler : IRequestHandler<CreateCustomerCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public CreateCustomerCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(CreateCustomerCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = _mapper.Map<Customer>(request);
        item.AddDomainEvent(new CustomerCreatedEvent(item));
        db.Customers.Add(item);
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
