//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Query for getting all JournalEntries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.JournalEntries.DTOs;
using CleanArchitecture.Blazor.Application.Features.JournalEntries.Caching;
using Microsoft.Extensions.Caching.Memory;

namespace CleanArchitecture.Blazor.Application.Features.JournalEntries.Queries.GetAll;

public class GetAllJournalEntriesQuery : ICacheableRequest<IEnumerable<JournalEntryDto>>
{
    public string CacheKey => JournalEntryCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags { get; }

    public MemoryCacheEntryOptions? Options => new MemoryCacheEntryOptions
    {
        AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(30)
    };
}

public class GetAllJournalEntriesQueryHandler : IRequestHandler<GetAllJournalEntriesQuery, IEnumerable<JournalEntryDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public GetAllJournalEntriesQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<IEnumerable<JournalEntryDto>> Handle(GetAllJournalEntriesQuery request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await db.JournalEntries
            .OrderByDescending(x => x.Date)
            .ToListAsync(cancellationToken);
        return _mapper.Map<List<JournalEntryDto>>(data);
    }
}
