//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// BillItemDto: transfers bill item data between layers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.BillItems.DTOs;

[Description("Bill Items")]
public class BillItemDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Bill ID")]
    public string? BillID { get; set; }
    
    [Description("Item Name")]
    public string? ItemName { get; set; }
    
    [Description("Quantity")]
    public int Quantity { get; set; }
    
    [Description("Unit Price")]
    public decimal UnitPrice { get; set; }
    
    [Description("Line Total")]
    public decimal LineTotal { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<BillItem, BillItemDto>(MemberList.None);
            CreateMap<BillItemDto, BillItem>(MemberList.None);
        }
    }
}
