//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Import command & template for vendors.
// Validates Excel data, prevents duplicates, and provides a template for bulk entry.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vendors.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Commands.Import;

public class ImportVendorsCommand : ICacheInvalidatorRequest<Result<int>>
{
    public string FileName { get; set; }
    public byte[] Data { get; set; }
    public string CacheKey => VendorCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => VendorCacheKey.Tags;
    
    public ImportVendorsCommand(string fileName, byte[] data)
    {
        FileName = fileName;
        Data = data;
    }
}

public record class CreateVendorsTemplateCommand : IRequest<Result<byte[]>>
{
}

public class ImportVendorsCommandHandler :
    IRequestHandler<CreateVendorsTemplateCommand, Result<byte[]>>,
    IRequestHandler<ImportVendorsCommand, Result<int>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IStringLocalizer<ImportVendorsCommandHandler> _localizer;
    private readonly IExcelService _excelService;
    private readonly VendorDto _dto = new();
    private readonly IMapper _mapper;

    public ImportVendorsCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper,
        IExcelService excelService,
        IStringLocalizer<ImportVendorsCommandHandler> localizer)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
        _excelService = excelService;
        _localizer = localizer;
    }

    public async Task<Result<byte[]>> Handle(CreateVendorsTemplateCommand request, CancellationToken cancellationToken)
    {
        var fields = new string[]
        {
            _localizer[_dto.GetMemberDescription(x => x.Name)],
            _localizer[_dto.GetMemberDescription(x => x.Email)],
            _localizer[_dto.GetMemberDescription(x => x.PhoneNumber)]
        };
        var result = await _excelService.CreateTemplateAsync(fields, _localizer[_dto.GetClassDescription()]);
        return await Result<byte[]>.SuccessAsync(result);
    }

    #nullable disable warnings
    public async Task<Result<int>> Handle(ImportVendorsCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var result = await _excelService.ImportAsync(request.Data, mappers: new Dictionary<string, Func<DataRow, VendorDto, object?>>
        {
            { _localizer[_dto.GetMemberDescription(x => x.Name)], (row, item) => item.Name = row[_localizer[_dto.GetMemberDescription(x => x.Name)]].ToString() },
            { _localizer[_dto.GetMemberDescription(x => x.Email)], (row, item) => item.Email = row[_localizer[_dto.GetMemberDescription(x => x.Email)]].ToString() },
            { _localizer[_dto.GetMemberDescription(x => x.PhoneNumber)], (row, item) => item.PhoneNumber = row[_localizer[_dto.GetMemberDescription(x => x.PhoneNumber)]].ToString() }
        }, _localizer[_dto.GetClassDescription()]);

        if (result.Succeeded && result.Data is not null)
        {
            foreach (var dto in result.Data)
            {
                var exists = await db.Vendors.AnyAsync(x => x.Name == dto.Name && x.Email == dto.Email, cancellationToken);
                if (!exists)
                {
                    var item = _mapper.Map<Vendor>(dto);
                    await db.Vendors.AddAsync(item, cancellationToken);
                }
            }
            await db.SaveChangesAsync(cancellationToken);
            return await Result<int>.SuccessAsync(result.Data.Count());
        }
        else
        {
            return await Result<int>.FailureAsync(result.Errors);
        }
    }
}
