//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Validator for ImportVendorsCommand: enforces file requirements for Vendor imports.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Commands.Import;

public class ImportVendorsCommandValidator : AbstractValidator<ImportVendorsCommand>
{
    public ImportVendorsCommandValidator()
    {
        RuleFor(v => v.Data).NotNull().NotEmpty();
        RuleFor(v => v.FileName).NotEmpty().MaximumLength(255);
    }
}
