//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for GeneralLedger, InvoiceItem, BillItem entities.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

// GeneralLedger Events
public class GeneralLedgerCreatedEvent : DomainEvent
{
    public GeneralLedgerCreatedEvent(GeneralLedger item) { Item = item; }
    public GeneralLedger Item { get; }
}

public class GeneralLedgerUpdatedEvent : DomainEvent
{
    public GeneralLedgerUpdatedEvent(GeneralLedger item) { Item = item; }
    public GeneralLedger Item { get; }
}

public class GeneralLedgerDeletedEvent : DomainEvent
{
    public GeneralLedgerDeletedEvent(GeneralLedger item) { Item = item; }
    public GeneralLedger Item { get; }
}

// InvoiceItem Events
public class InvoiceItemCreatedEvent : DomainEvent
{
    public InvoiceItemCreatedEvent(InvoiceItem item) { Item = item; }
    public InvoiceItem Item { get; }
}

public class InvoiceItemUpdatedEvent : DomainEvent
{
    public InvoiceItemUpdatedEvent(InvoiceItem item) { Item = item; }
    public InvoiceItem Item { get; }
}

public class InvoiceItemDeletedEvent : DomainEvent
{
    public InvoiceItemDeletedEvent(InvoiceItem item) { Item = item; }
    public InvoiceItem Item { get; }
}

// BillItem Events
public class BillItemCreatedEvent : DomainEvent
{
    public BillItemCreatedEvent(BillItem item) { Item = item; }
    public BillItem Item { get; }
}

public class BillItemUpdatedEvent : DomainEvent
{
    public BillItemUpdatedEvent(BillItem item) { Item = item; }
    public BillItem Item { get; }
}

public class BillItemDeletedEvent : DomainEvent
{
    public BillItemDeletedEvent(BillItem item) { Item = item; }
    public BillItem Item { get; }
}
