//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for Vendor, Invoice, Payment, Bill entities.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

// Vendor Events
public class VendorCreatedEvent : DomainEvent
{
    public VendorCreatedEvent(Vendor item) { Item = item; }
    public Vendor Item { get; }
}

public class VendorUpdatedEvent : DomainEvent
{
    public VendorUpdatedEvent(Vendor item) { Item = item; }
    public Vendor Item { get; }
}

public class VendorDeletedEvent : DomainEvent
{
    public VendorDeletedEvent(Vendor item) { Item = item; }
    public Vendor Item { get; }
}

// Invoice Events
public class InvoiceCreatedEvent : DomainEvent
{
    public InvoiceCreatedEvent(Invoice item) { Item = item; }
    public Invoice Item { get; }
}

public class InvoiceUpdatedEvent : DomainEvent
{
    public InvoiceUpdatedEvent(Invoice item) { Item = item; }
    public Invoice Item { get; }
}

public class InvoiceDeletedEvent : DomainEvent
{
    public InvoiceDeletedEvent(Invoice item) { Item = item; }
    public Invoice Item { get; }
}

// Payment Events
public class PaymentCreatedEvent : DomainEvent
{
    public PaymentCreatedEvent(Payment item) { Item = item; }
    public Payment Item { get; }
}

public class PaymentUpdatedEvent : DomainEvent
{
    public PaymentUpdatedEvent(Payment item) { Item = item; }
    public Payment Item { get; }
}

public class PaymentDeletedEvent : DomainEvent
{
    public PaymentDeletedEvent(Payment item) { Item = item; }
    public Payment Item { get; }
}

// Bill Events
public class BillCreatedEvent : DomainEvent
{
    public BillCreatedEvent(Bill item) { Item = item; }
    public Bill Item { get; }
}

public class BillUpdatedEvent : DomainEvent
{
    public BillUpdatedEvent(Bill item) { Item = item; }
    public Bill Item { get; }
}

public class BillDeletedEvent : DomainEvent
{
    public BillDeletedEvent(Bill item) { Item = item; }
    public Bill Item { get; }
}
