//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for Bill entity.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class BillCreatedEvent : DomainEvent
{
    public BillCreatedEvent(Bill item)
    {
        Item = item;
    }

    public Bill Item { get; }
}

public class BillUpdatedEvent : DomainEvent
{
    public BillUpdatedEvent(Bill item)
    {
        Item = item;
    }

    public Bill Item { get; }
}

public class BillDeletedEvent : DomainEvent
{
    public BillDeletedEvent(Bill item)
    {
        Item = item;
    }

    public Bill Item { get; }
}
