//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for BillItem entity.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class BillItemCreatedEvent : DomainEvent
{
    public BillItemCreatedEvent(BillItem item)
    {
        Item = item;
    }

    public BillItem Item { get; }
}

public class BillItemUpdatedEvent : DomainEvent
{
    public BillItemUpdatedEvent(BillItem item)
    {
        Item = item;
    }

    public BillItem Item { get; }
}

public class BillItemDeletedEvent : DomainEvent
{
    public BillItemDeletedEvent(BillItem item)
    {
        Item = item;
    }

    public BillItem Item { get; }
}
