//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Represents a domain event that occurs when a chart of account is updated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class ChartOfAccountUpdatedEvent : DomainEvent
{
    public ChartOfAccountUpdatedEvent(ChartOfAccount item)
    {
        Item = item;
    }

    public ChartOfAccount Item { get; }
}

public class ChartOfAccountDeletedEvent : DomainEvent
{
    public ChartOfAccountDeletedEvent(ChartOfAccount item)
    {
        Item = item;
    }

    public ChartOfAccount Item { get; }
}
