//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Represents a domain event that occurs when a new chart of account is created.
//       Used to signal other parts of the system that a new chart of account has been added.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class ChartOfAccountCreatedEvent : DomainEvent
{
    public ChartOfAccountCreatedEvent(ChartOfAccount item)
    {
        Item = item;
    }

    public ChartOfAccount Item { get; }
}
