//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for GeneralLedger entity.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class GeneralLedgerCreatedEvent : DomainEvent
{
    public GeneralLedgerCreatedEvent(GeneralLedger item)
    {
        Item = item;
    }

    public GeneralLedger Item { get; }
}

public class GeneralLedgerUpdatedEvent : DomainEvent
{
    public GeneralLedgerUpdatedEvent(GeneralLedger item)
    {
        Item = item;
    }

    public GeneralLedger Item { get; }
}

public class GeneralLedgerDeletedEvent : DomainEvent
{
    public GeneralLedgerDeletedEvent(GeneralLedger item)
    {
        Item = item;
    }

    public GeneralLedger Item { get; }
}
