//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for InvoiceItem entity.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class InvoiceItemCreatedEvent : DomainEvent
{
    public InvoiceItemCreatedEvent(InvoiceItem item)
    {
        Item = item;
    }

    public InvoiceItem Item { get; }
}

public class InvoiceItemUpdatedEvent : DomainEvent
{
    public InvoiceItemUpdatedEvent(InvoiceItem item)
    {
        Item = item;
    }

    public InvoiceItem Item { get; }
}

public class InvoiceItemDeletedEvent : DomainEvent
{
    public InvoiceItemDeletedEvent(InvoiceItem item)
    {
        Item = item;
    }

    public InvoiceItem Item { get; }
}
