//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for Invoice entity.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class InvoiceCreatedEvent : DomainEvent
{
    public InvoiceCreatedEvent(Invoice item)
    {
        Item = item;
    }

    public Invoice Item { get; }
}

public class InvoiceUpdatedEvent : DomainEvent
{
    public InvoiceUpdatedEvent(Invoice item)
    {
        Item = item;
    }

    public Invoice Item { get; }
}

public class InvoiceDeletedEvent : DomainEvent
{
    public InvoiceDeletedEvent(Invoice item)
    {
        Item = item;
    }

    public Invoice Item { get; }
}
