//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for JournalEntry entity.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class JournalEntryCreatedEvent : DomainEvent
{
    public JournalEntryCreatedEvent(JournalEntry item)
    {
        Item = item;
    }

    public JournalEntry Item { get; }
}

public class JournalEntryUpdatedEvent : DomainEvent
{
    public JournalEntryUpdatedEvent(JournalEntry item)
    {
        Item = item;
    }

    public JournalEntry Item { get; }
}

public class JournalEntryDeletedEvent : DomainEvent
{
    public JournalEntryDeletedEvent(JournalEntry item)
    {
        Item = item;
    }

    public JournalEntry Item { get; }
}
