//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for Payment entity.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class PaymentCreatedEvent : DomainEvent
{
    public PaymentCreatedEvent(Payment item)
    {
        Item = item;
    }

    public Payment Item { get; }
}

public class PaymentUpdatedEvent : DomainEvent
{
    public PaymentUpdatedEvent(Payment item)
    {
        Item = item;
    }

    public Payment Item { get; }
}

public class PaymentDeletedEvent : DomainEvent
{
    public PaymentDeletedEvent(Payment item)
    {
        Item = item;
    }

    public Payment Item { get; }
}
