//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Domain events for Vendor entity.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Domain.Events;

public class VendorCreatedEvent : DomainEvent
{
    public VendorCreatedEvent(Vendor item)
    {
        Item = item;
    }

    public Vendor Item { get; }
}

public class VendorUpdatedEvent : DomainEvent
{
    public VendorUpdatedEvent(Vendor item)
    {
        Item = item;
    }

    public Vendor Item { get; }
}

public class VendorDeletedEvent : DomainEvent
{
    public VendorDeletedEvent(Vendor item)
    {
        Item = item;
    }

    public Vendor Item { get; }
}
