//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// InvoiceItemDto: transfers invoice item data between layers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.InvoiceItems.DTOs;

[Description("Invoice Items")]
public class InvoiceItemDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Invoice Id")]
    public string? InvoiceId { get; set; }
    
    [Description("Quantity")]
    public int Quantity { get; set; }
    
    [Description("Unit Price")]
    public decimal UnitPrice { get; set; }
    
    [Description("Line Total")]
    public decimal LineTotal { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }
    [Description("Name")]
    public string Name { get; set; }
    [Description("Description")]
    public string? Description { get; set; }
    [Description("Notes")]
    public string? Notes { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<InvoiceItem, InvoiceItemDto>(MemberList.None);
            CreateMap<InvoiceItemDto, InvoiceItem>(MemberList.None);
        }
    }
}
