//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for updating a JournalEntry.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.JournalEntries.Caching;

namespace CleanArchitecture.Blazor.Application.Features.JournalEntries.Commands.Update;

public class UpdateJournalEntryCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Date")]
    public DateTime Date { get; set; }
    
    [Description("Reference Number")]
    public string? ReferenceNumber { get; set; }
    
    [Description("Description")]
    public string? Description { get; set; }
    
    [Description("Source")]
    public string? Source { get; set; }
    
    [Description("Is Posted")]
    public bool IsPosted { get; set; }

    public string CacheKey => JournalEntryCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => JournalEntryCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateJournalEntryCommand, JournalEntry>(MemberList.None);
        }
    }
}

public class UpdateJournalEntryCommandHandler : IRequestHandler<UpdateJournalEntryCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public UpdateJournalEntryCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(UpdateJournalEntryCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.JournalEntries.FindAsync(new object[] { request.Id }, cancellationToken);
        if (item == null)
        {
            return await Result<string>.FailureAsync($"Journal Entry with id: {request.Id} not found.");
        }
        item = _mapper.Map(request, item);
        item.AddDomainEvent(new JournalEntryUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
