//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// CustomerDto: transfers customer data between layers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Customers.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Customers.DTOs;

[Description("Customers")]
public class CustomerDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Customer Name")]
    public string? Name { get; set; }
    
    [Description("Description")]
    public string? Description { get; set; }
    [Description("Notes")]
    public string? Notes { get; set; }
    
    [Description("Billing Address")]
    public string? BillingAddress { get; set; }
    
    [Description("Phone Number")]
    public string? PhoneNumber { get; set; }
    
    [Description("Email")]
    public string? Email { get; set; }
    
    [Description("Terms")]
    public string? Terms { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Customer, CustomerDto>(MemberList.None);
            CreateMap<CustomerDto, Customer>(MemberList.None);
        }
    }
}
