//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Advanced filter and specification for Vendor queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Specifications;

public enum VendorListView
{
    [Description("All")]
    All,
    [Description("Active")]
    Active,
    [Description("With Email")]
    WithEmail
}

public class VendorAdvancedFilter : PaginationFilter
{
    public VendorListView ListView { get; set; } = VendorListView.All;
    public string? Country { get; set; }
    public string? Terms { get; set; }
}

public class VendorAdvancedSpecification : Specification<Vendor>
{
    public VendorAdvancedSpecification(VendorAdvancedFilter filter)
    {
        Query.Where(q => q.Name != null)
             .Where(filter.Keyword, !string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.BillingAddress != null)
             .Where(q => q.Terms == filter.Terms, !string.IsNullOrEmpty(filter.Terms));

        switch (filter.ListView)
        {
            case VendorListView.All:
                break;
            case VendorListView.Active:
                Query.Where(q => q.Created != null);
                break;
            case VendorListView.WithEmail:
                Query.Where(q => !string.IsNullOrEmpty(q.Email));
                break;
        }
    }
}
