//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// BillDto: transfers bill data between layers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Bills.DTOs;

[Description("Bills")]
public class BillDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Vendor ID")]
    public string? VendorID { get; set; }
    
    [Description("Bill Date")]
    public DateTime BillDate { get; set; }
    
    [Description("Due Date")]
    public DateTime DueDate { get; set; }
    
    [Description("Total Amount")]
    public decimal TotalAmount { get; set; }
    
    [Description("Status")]
    public BillStatus Status { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Bill, BillDto>(MemberList.None);
            CreateMap<BillDto, Bill>(MemberList.None);
        }
    }
}
