//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Query for retrieving a single bill by its unique identifier.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Bills.DTOs;
using CleanArchitecture.Blazor.Application.Features.Bills.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Bills.Queries.GetById;

public class GetBillByIdQuery : ICacheableRequest<Result<BillDto>>
{
    public required string Id { get; set; }
    public string CacheKey => BillCacheKey.GetByIdCacheKey($"{Id}");
    public IEnumerable<string>? Tags => BillCacheKey.Tags;
}

public class GetBillByIdQueryHandler : IRequestHandler<GetBillByIdQuery, Result<BillDto>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public GetBillByIdQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<BillDto>> Handle(GetBillByIdQuery request, CancellationToken cancellationToken)
    {
        await using var context = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await context.Bills
            .Where(x => x.Id == request.Id)
            .ProjectTo<BillDto>(_mapper.ConfigurationProvider)
            .FirstOrDefaultAsync(cancellationToken);

        if (item == null)
        {
            return await Result<BillDto>.FailureAsync($"Bill with id: [{request.Id}] not found.");
        }

        return await Result<BillDto>.SuccessAsync(item);
    }
}
