//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Defines a query to export bill data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified bill details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Bills.DTOs;
using CleanArchitecture.Blazor.Application.Features.Bills.Caching;
using CleanArchitecture.Blazor.Application.Features.Bills.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Bills.Queries.Export;

public class ExportBillsQuery : BillAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
    public BillAdvancedSpecification Specification => new BillAdvancedSpecification(this);
    public IEnumerable<string>? Tags => BillCacheKey.Tags;
    
    public override string ToString()
    {
        return $"Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    
    public string CacheKey => BillCacheKey.GetExportCacheKey($"{this}");
}

public class ExportBillsQueryHandler : IRequestHandler<ExportBillsQuery, Result<byte[]>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    private readonly IExcelService _excelService;
    private readonly IStringLocalizer<ExportBillsQueryHandler> _localizer;
    private readonly BillDto _dto = new();

    public ExportBillsQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper,
        IExcelService excelService,
        IStringLocalizer<ExportBillsQueryHandler> localizer)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
        _excelService = excelService;
        _localizer = localizer;
    }

    public async Task<Result<byte[]>> Handle(ExportBillsQuery request, CancellationToken cancellationToken)
    {
        await using var context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await context.Bills.ApplySpecification(request.Specification)
            .OrderBy($"{request.OrderBy} {request.SortDirection}")
            .ProjectTo<BillDto>(_mapper.ConfigurationProvider)
            .AsNoTracking()
            .ToListAsync(cancellationToken);

        var result = await _excelService.ExportAsync(data,
            new Dictionary<string, Func<BillDto, object?>>()
            {
                { _localizer[_dto.GetMemberDescription(x => x.VendorId)], item => item.VendorId },
                { _localizer[_dto.GetMemberDescription(x => x.BillDate)], item => item.BillDate },
                { _localizer[_dto.GetMemberDescription(x => x.DueDate)], item => item.DueDate },
                { _localizer[_dto.GetMemberDescription(x => x.TotalAmount)], item => item.TotalAmount },
                { _localizer[_dto.GetMemberDescription(x => x.Status)], item => item.Status }
            }, _localizer["Bills"]);

        return await Result<byte[]>.SuccessAsync(result);
    }
}
