//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Validator for AddEditCustomerCommand: enforces field length and required property rules for Customer entities.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Customers.Commands.AddEdit;

public class AddEditCustomerCommandValidator : AbstractValidator<AddEditCustomerCommand>
{
    public AddEditCustomerCommandValidator()
    {
        RuleFor(v => v.Name).MaximumLength(100).NotEmpty();
        RuleFor(v => v.Description).MaximumLength(500);
        RuleFor(v => v.Email).MaximumLength(255).EmailAddress().When(v => !string.IsNullOrWhiteSpace(v.Email));
        RuleFor(v => v.PhoneNumber).MaximumLength(50);
        RuleFor(v => v.Country).MaximumLength(100);
    }
}
