//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Defines a query to export customer data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified customer details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Customers.DTOs;
using CleanArchitecture.Blazor.Application.Features.Customers.Caching;
using CleanArchitecture.Blazor.Application.Features.Customers.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Customers.Queries.Export;

public class ExportCustomersQuery : CustomerAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
    public CustomerAdvancedSpecification Specification => new CustomerAdvancedSpecification(this);
    public IEnumerable<string>? Tags => CustomerCacheKey.Tags;
    
    public override string ToString()
    {
        return $"Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    
    public string CacheKey => CustomerCacheKey.GetExportCacheKey($"{this}");
}

public class ExportCustomersQueryHandler : IRequestHandler<ExportCustomersQuery, Result<byte[]>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    private readonly IExcelService _excelService;
    private readonly IStringLocalizer<ExportCustomersQueryHandler> _localizer;
    private readonly CustomerDto _dto = new();

    public ExportCustomersQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper,
        IExcelService excelService,
        IStringLocalizer<ExportCustomersQueryHandler> localizer)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
        _excelService = excelService;
        _localizer = localizer;
    }

    public async Task<Result<byte[]>> Handle(ExportCustomersQuery request, CancellationToken cancellationToken)
    {
        await using var context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await context.Customers.ApplySpecification(request.Specification)
            .OrderBy($"{request.OrderBy} {request.SortDirection}")
            .ProjectTo<CustomerDto>(_mapper.ConfigurationProvider)
            .AsNoTracking()
            .ToListAsync(cancellationToken);

        var result = await _excelService.ExportAsync(data,
            new Dictionary<string, Func<CustomerDto, object?>>()
            {
                { _localizer[_dto.GetMemberDescription(x => x.Name)], item => item.Name },
                { _localizer[_dto.GetMemberDescription(x => x.Email)], item => item.Email },
                { _localizer[_dto.GetMemberDescription(x => x.PhoneNumber)], item => item.PhoneNumber },
                { _localizer[_dto.GetMemberDescription(x => x.Description)], item => item.Description },
                { _localizer[_dto.GetMemberDescription(x => x.Notes)], item => item.Notes }
            }, _localizer["Customers"]);

        return await Result<byte[]>.SuccessAsync(result);
    }
}
