//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command for adding/editing an invoice entity with validation, mapping,
// domain events, and cache invalidation.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Invoices.Caching;
using CleanArchitecture.Blazor.Application.Features.Invoices.DTOs;

namespace CleanArchitecture.Blazor.Application.Features.Invoices.Commands.AddEdit;

public class AddEditInvoiceCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string? Id { get; set; }
    [Description("Customer Id")]
    public string? CustomerId { get; set; }
    [Description("Invoice Date")]
    public DateTime InvoiceDate { get; set; } = DateTime.Now;
    [Description("Due Date")]
    public DateTime DueDate { get; set; }
    [Description("Total Amount")]
    public decimal TotalAmount { get; set; }
    [Description("Status")]
    public InvoiceStatus Status { get; set; } = InvoiceStatus.Open;

    public string CacheKey => InvoiceCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => InvoiceCacheKey.Tags;

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<InvoiceDto, AddEditInvoiceCommand>(MemberList.None);
            CreateMap<AddEditInvoiceCommand, Invoice>(MemberList.None);
        }
    }
}

public class AddEditInvoiceCommandHandler : IRequestHandler<AddEditInvoiceCommand, Result<string>>
{
    private readonly IMapper _mapper;
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public AddEditInvoiceCommandHandler(
        IMapper mapper,
        IApplicationDbContextFactory dbContextFactory)
    {
        _mapper = mapper;
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<string>> Handle(AddEditInvoiceCommand request, CancellationToken cancellationToken)
    {
        await using var context = await _dbContextFactory.CreateAsync(cancellationToken);
        if (request.Id is not null)
        {
            var item = await context.Invoices.FindAsync([request.Id], cancellationToken);
            if (item is null)
            {
                return await Result<string>.FailureAsync($"Invoice with id: [{request.Id}] not found.");
            }
            item = _mapper.Map(request, item);
            await context.SaveChangesAsync(cancellationToken);
            return await Result<string>.SuccessAsync(item.Id);
        }
        else
        {
            var item = _mapper.Map<Invoice>(request);
            
            context.Invoices.Add(item);
            await context.SaveChangesAsync(cancellationToken);
            return await Result<string>.SuccessAsync(item.Id);
        }
    }
}
