//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Validator for AddEditInvoiceCommand: enforces field length and required property rules for Invoice entities.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Invoices.Commands.AddEdit;

public class AddEditInvoiceCommandValidator : AbstractValidator<AddEditInvoiceCommand>
{
    public AddEditInvoiceCommandValidator()
    {
        RuleFor(v => v.CustomerId).MaximumLength(100).NotEmpty();
        RuleFor(v => v.InvoiceDate).NotEmpty();
        RuleFor(v => v.DueDate).NotEmpty().GreaterThanOrEqualTo(v => v.InvoiceDate);
        RuleFor(v => v.TotalAmount).GreaterThan(0);
        RuleFor(v => v.Status).IsInEnum().NotNull();
    }
}
