//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-08-04
//     Last Modified: 2025-08-04
//     Description: 
//       Defines a query to export vendor data to an Excel file. This query 
//       applies advanced filtering options and generates an Excel file with 
//       the specified vendor details.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Vendors.DTOs;
using CleanArchitecture.Blazor.Application.Features.Vendors.Caching;
using CleanArchitecture.Blazor.Application.Features.Vendors.Specifications;

namespace CleanArchitecture.Blazor.Application.Features.Vendors.Queries.Export;

public class ExportVendorsQuery : VendorAdvancedFilter, ICacheableRequest<Result<byte[]>>
{
    public VendorAdvancedSpecification Specification => new VendorAdvancedSpecification(this);
    public IEnumerable<string>? Tags => VendorCacheKey.Tags;
    
    public override string ToString()
    {
        return $"Search:{Keyword}, {OrderBy}, {SortDirection}";
    }
    
    public string CacheKey => VendorCacheKey.GetExportCacheKey($"{this}");
}

public class ExportVendorsQueryHandler : IRequestHandler<ExportVendorsQuery, Result<byte[]>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;
    private readonly IExcelService _excelService;
    private readonly IStringLocalizer<ExportVendorsQueryHandler> _localizer;
    private readonly VendorDto _dto = new();

    public ExportVendorsQueryHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper,
        IExcelService excelService,
        IStringLocalizer<ExportVendorsQueryHandler> localizer)
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
        _excelService = excelService;
        _localizer = localizer;
    }

    public async Task<Result<byte[]>> Handle(ExportVendorsQuery request, CancellationToken cancellationToken)
    {
        await using var context = await _dbContextFactory.CreateAsync(cancellationToken);
        var data = await context.Vendors.ApplySpecification(request.Specification)
            .OrderBy($"{request.OrderBy} {request.SortDirection}")
            .ProjectTo<VendorDto>(_mapper.ConfigurationProvider)
            .AsNoTracking()
            .ToListAsync(cancellationToken);

        var result = await _excelService.ExportAsync(data,
            new Dictionary<string, Func<VendorDto, object?>>()
            {
                { _localizer[_dto.GetMemberDescription(x => x.Name)], item => item.Name },
                { _localizer[_dto.GetMemberDescription(x => x.Email)], item => item.Email },
                { _localizer[_dto.GetMemberDescription(x => x.PhoneNumber)], item => item.PhoneNumber },
                { _localizer[_dto.GetMemberDescription(x => x.Description)], item => item.Description },
                { _localizer[_dto.GetMemberDescription(x => x.Notes)], item => item.Notes },
            }, _localizer["Vendors"]);

        return await Result<byte[]>.SuccessAsync(result);
    }
}
