//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// VendorDto: transfers vendor data between layers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Vendors.DTOs;

[Description("Vendors")]
public class VendorDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Vendor Name")]
    public string? VendorName { get; set; }
    
    [Description("Billing Address")]
    public string? BillingAddress { get; set; }
    
    [Description("Contact Person")]
    public string? ContactPerson { get; set; }
    
    [Description("Email")]
    public string? Email { get; set; }
    
    [Description("Terms")]
    public string? Terms { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Vendor, VendorDto>(MemberList.None);
            CreateMap<VendorDto, Vendor>(MemberList.None);
        }
    }
}
