//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for deleting Payment(s).
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Payments.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Payments.Commands.Delete;

public class DeletePaymentCommand : ICacheInvalidatorRequest<Result<string>>
{
    public string[] Ids { get; set; } = Array.Empty<string>();
    public string CacheKey => PaymentCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => PaymentCacheKey.Tags;
}

public class DeletePaymentCommandHandler : IRequestHandler<DeletePaymentCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;

    public DeletePaymentCommandHandler(IApplicationDbContextFactory dbContextFactory)
    {
        _dbContextFactory = dbContextFactory;
    }

    public async Task<Result<string>> Handle(DeletePaymentCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var items = await db.Payments.Where(x => request.Ids.Contains(x.Id)).ToListAsync(cancellationToken);
        foreach (var item in items)
        {
            item.AddDomainEvent(new PaymentDeletedEvent(item));
            db.Payments.Remove(item);
        }
        var result = await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync($"Deleted {result} payments.");
    }
}
