//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Defines permission constants for customer operations (view, create, edit, delete, etc.).
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Blazor.Application.Common.Security;

public static partial class Permissions
{
    [DisplayName("Customer Permissions")]
    [Description("Set permissions for customer operations.")]
    public static class Customers
    {
        [Description("Allows viewing customer details.")]
        public const string View = "Permissions.Customers.View";
        [Description("Allows creating customer records.")]
        public const string Create = "Permissions.Customers.Create";
        [Description("Allows modifying existing customer details.")]
        public const string Edit = "Permissions.Customers.Edit";
        [Description("Allows deleting customer records.")]
        public const string Delete = "Permissions.Customers.Delete";
        [Description("Allows printing customer details.")]
        public const string Print = "Permissions.Customers.Print";
        [Description("Allows searching customer records.")]
        public const string Search = "Permissions.Customers.Search";
        [Description("Allows exporting customer records.")]
        public const string Export = "Permissions.Customers.Export";
        [Description("Allows importing customer records.")]
        public const string Import = "Permissions.Customers.Import";
    }
}

public class CustomersAccessRights
{
    public bool View { get; set; }
    public bool Create { get; set; }
    public bool Edit { get; set; }
    public bool Delete { get; set; }
    public bool Print { get; set; }
    public bool Search { get; set; }
    public bool Export { get; set; }
    public bool Import { get; set; }
}
