//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for creating a new Payment.
// Uses caching invalidation and domain events for data consistency.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Payments.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Payments.Commands.Create;

public class CreatePaymentCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Customer Id")]
    public string? CustomerID { get; set; }
    
    [Description("Payment Date")]
    public DateTime PaymentDate { get; set; } = DateTime.Now;
    
    [Description("Amount")]
    public decimal Amount { get; set; }
    
    [Description("Payment Method")]
    public PaymentMethod PaymentMethod { get; set; } = PaymentMethod.Cash;
    
    [Description("Reference Number")]
    public string? ReferenceNumber { get; set; }

    public string CacheKey => PaymentCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => PaymentCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<CreatePaymentCommand, Payment>(MemberList.None);
        }
    }
}

public class CreatePaymentCommandHandler : IRequestHandler<CreatePaymentCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public CreatePaymentCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(CreatePaymentCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = _mapper.Map<Payment>(request);
        item.AddDomainEvent(new PaymentCreatedEvent(item));
        db.Payments.Add(item);
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
