//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// PaymentDto: transfers payment data between layers.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Payments.DTOs;

[Description("Payments")]
public class PaymentDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Customer Id")]
    public string? CustomerId { get; set; }
    
    [Description("Payment Date")]
    public DateTime PaymentDate { get; set; }
    
    [Description("Amount")]
    public decimal Amount { get; set; }
    
    [Description("Payment Method")]
    public PaymentMethod PaymentMethod { get; set; }
    
    [Description("Reference Number")]
    public string? ReferenceNumber { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }

    [Description("Name")]
    public string Name { get; set; } = string.Empty;
    [Description("Description")]
    public string? Description { get; set; }
    [Description("Notes")]
    public string? Notes { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Payment, PaymentDto>(MemberList.None);
            CreateMap<PaymentDto, Payment>(MemberList.None);
        }
    }
}
