//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// ChartOfAccountDto: transfers chart of account data between layers.
// Docs: https://docs.cleanarchitectureblazor.com/features/chartofaccount
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.ChartOfAccounts.DTOs;

[Description("Chart of Accounts")]
public class ChartOfAccountDto
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Account Name")]
    public string? AccountName { get; set; }
    
    [Description("Account Type")]
    public AccountType AccountType { get; set; }
    
    [Description("Sub Account Of")]
    public string? SubAccountOf { get; set; }
    
    [Description("Description")]
    public string? Description { get; set; }
    
    [Description("Is Active")]
    public bool IsActive { get; set; }
    
    [Description("Created")]
    public DateTime? Created { get; set; }
    
    [Description("Created By")]
    public string? CreatedBy { get; set; }
    
    [Description("Last Modified")]
    public DateTime? LastModified { get; set; }
    
    [Description("Last Modified By")]
    public string? LastModifiedBy { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<ChartOfAccount, ChartOfAccountDto>(MemberList.None);
            CreateMap<ChartOfAccountDto, ChartOfAccount>(MemberList.None);
        }
    }
}
