//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for updating a Payment.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Payments.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Payments.Commands.Update;

public class UpdatePaymentCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Customer Id")]
    public string? CustomerID { get; set; }
    
    [Description("Payment Date")]
    public DateTime PaymentDate { get; set; }
    
    [Description("Amount")]
    public decimal Amount { get; set; }
    
    [Description("Payment Method")]
    public PaymentMethod PaymentMethod { get; set; }
    
    [Description("Reference Number")]
    public string? ReferenceNumber { get; set; }

    public string CacheKey => PaymentCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => PaymentCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdatePaymentCommand, Payment>(MemberList.None);
        }
    }
}

public class UpdatePaymentCommandHandler : IRequestHandler<UpdatePaymentCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public UpdatePaymentCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(UpdatePaymentCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.Payments.FindAsync(new object[] { request.Id }, cancellationToken);
        if (item == null)
        {
            return await Result<string>.FailureAsync($"Payment with id: {request.Id} not found.");
        }
        item = _mapper.Map(request, item);
        item.AddDomainEvent(new PaymentUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
