//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Advanced filter and specification for Customer queries.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

namespace CleanArchitecture.Blazor.Application.Features.Customers.Specifications;

public enum CustomerListView
{
    [Description("All")]
    All,
    [Description("Active")]
    Active,
    [Description("With Email")]
    WithEmail
}

public class CustomerAdvancedFilter : PaginationFilter
{
    public CustomerListView ListView { get; set; } = CustomerListView.All;
    public string? Country { get; set; }
    public string? Terms { get; set; }
}

public class CustomerAdvancedSpecification : Specification<Customer>
{
    public CustomerAdvancedSpecification(CustomerAdvancedFilter filter)
    {
        Query.Where(q => q.CustomerName != null)
             .Where(filter.Keyword, !string.IsNullOrEmpty(filter.Keyword))
             .Where(q => q.BillingAddress != null)
             .Where(q => q.Terms == filter.Terms, !string.IsNullOrEmpty(filter.Terms));

        switch (filter.ListView)
        {
            case CustomerListView.All:
                break;
            case CustomerListView.Active:
                Query.Where(q => q.Created != null);
                break;
            case CustomerListView.WithEmail:
                Query.Where(q => !string.IsNullOrEmpty(q.Email));
                break;
        }
    }
}
