//------------------------------------------------------------------------------
// <auto-generated>
// CleanArchitecture.Blazor - MIT Licensed.
// Author: neozhu
// Created/Modified: 2025-08-04
// Command and handler for updating a Bill.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#nullable disable warnings

using CleanArchitecture.Blazor.Application.Features.Bills.Caching;

namespace CleanArchitecture.Blazor.Application.Features.Bills.Commands.Update;

public class UpdateBillCommand : ICacheInvalidatorRequest<Result<string>>
{
    [Description("Id")]
    public string Id { get; set; } = string.Empty;
    
    [Description("Vendor ID")]
    public string? VendorID { get; set; }
    
    [Description("Bill Date")]
    public DateTime BillDate { get; set; }
    
    [Description("Due Date")]
    public DateTime DueDate { get; set; }
    
    [Description("Total Amount")]
    public decimal TotalAmount { get; set; }
    
    [Description("Status")]
    public BillStatus Status { get; set; }

    public string CacheKey => BillCacheKey.GetAllCacheKey;
    public IEnumerable<string>? Tags => BillCacheKey.Tags;
    
    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<UpdateBillCommand, Bill>(MemberList.None);
        }
    }
}

public class UpdateBillCommandHandler : IRequestHandler<UpdateBillCommand, Result<string>>
{
    private readonly IApplicationDbContextFactory _dbContextFactory;
    private readonly IMapper _mapper;

    public UpdateBillCommandHandler(
        IApplicationDbContextFactory dbContextFactory,
        IMapper mapper
    )
    {
        _dbContextFactory = dbContextFactory;
        _mapper = mapper;
    }

    public async Task<Result<string>> Handle(UpdateBillCommand request, CancellationToken cancellationToken)
    {
        await using var db = await _dbContextFactory.CreateAsync(cancellationToken);
        var item = await db.Bills.FindAsync(new object[] { request.Id }, cancellationToken);
        if (item == null)
        {
            return await Result<string>.FailureAsync($"Bill with id: {request.Id} not found.");
        }
        item = _mapper.Map(request, item);
        item.AddDomainEvent(new BillUpdatedEvent(item));
        await db.SaveChangesAsync(cancellationToken);
        return await Result<string>.SuccessAsync(item.Id);
    }
}
